version: "3.3"
networks:

  default:
    driver: bridge

services:
  jenkins:
    image: tobecrazy/jenkins:latest
    container_name: jenkins
    restart: always
    privileged: true
    environment:
      TZ: 'Asia/Shanghai'
    ports:
     - "8888:8080"
     - "50000:50000"
    networks:
     - default
    volumes:
     - ./export/jenkins:/var/jenkins_home
    mem_limit: 2G
